import {build} from 'esbuild';
import {mkdir,writeFile,copyFile} from 'node:fs/promises';
const out='.runtime/reference-qa/assets';
await mkdir(out+'/public',{recursive:true});
await mkdir('.runtime/reference-qa/res/values',{recursive:true});
await writeFile('.runtime/reference-qa/res/values/strings.xml','<resources><string name="app_name">ClearPair Reference QA</string><string name="title_activity_main">ClearPair Reference QA</string></resources>');
await build({entryPoints:['tools/reference-qa/probe.ts'],bundle:true,format:'esm',platform:'browser',outfile:out+'/public/probe.js'});
await build({entryPoints:['src/reference-score.worker.ts'],bundle:true,format:'esm',platform:'browser',outfile:out+'/public/reference-score.worker.js'});
await writeFile(out+'/public/index.html','<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><h1>ClearPair Reference QA</h1><pre id="result">Running…</pre><script type="module" src="probe.js"></script></body></html>');
for(const name of ['capacitor.config.json','capacitor.plugins.json'])await copyFile('native/apps/handf/android/app/src/main/assets/'+name,out+'/'+name);
console.log(out);
