const style='body{max-width:760px;margin:40px auto;padding:0 24px;font:16px/1.7 system-ui,sans-serif;color:#24293d;background:#f7f8fc}h1{line-height:1.2}h2{margin-top:32px;font-size:22px}a{color:#315eb7}:focus-visible{outline:3px solid #315eb7;outline-offset:4px}';
function page(title,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · ClearPair</title><meta name="description" content="ClearPair privacy and support for seven focused pronunciation apps."><style>${style}</style></head><body><nav><a href="/">ClearPair home</a> · <a href="/support.html">Support</a> · <a href="/privacy.html">Privacy</a></nav><main><h1>${title}</h1>${body}</main></body></html>`;}
export function privacyPage(){return page('ClearPair privacy policy',`
<p>Updated 1 October 2026. This policy covers ClearPair H &amp; F, L &amp; R, English, Mandarin, Korean, Arabic Letters and Cantonese, on iPhone/iPad, Android and the web. ClearPair is provided by LazyingArt.</p>
<h2>Your recordings stay on your device</h2>
<p>With your permission, the microphone records a practice take of up to 12 seconds. The app uses that audio locally for the waveform, recording-signal inspection, playback and recording history. ClearPair does not upload microphone recordings to an AI, transcription or pronunciation-scoring service.</p>
<p>Recordings, selected interface language, review progress and game stars are stored in app/browser storage on your device. They are not collected into a ClearPair account. Your operating system's backup or device-transfer settings may also apply. Export important takes before clearing data or uninstalling.</p>
<h2>Reference voices and network requests</h2>
<p>Reference pronunciation uses your installed device speech provider unless an approved clip is bundled. That provider may send the displayed reference text to its own network voice service, under its own terms and settings. ClearPair does not send your microphone take to that provider. Voice quality and offline availability depend on the device and installed voice.</p>
<p>The web version downloads app files from language-agent.lazying.art. Like other websites, its hosting infrastructure processes request details such as IP address, requested path and browser information for serving and securing the site. These requests do not contain your saved recordings or learning history.</p>
<h2>No advertising or tracking SDK</h2>
<p>These apps do not include advertising, behavioral analytics, tracking SDKs, login, social messaging or an in-app cloud account. Buying an app or installing a beta is handled by Apple or Google under their privacy policies; ClearPair does not receive your payment-card details.</p>
<h2>You control sharing and deletion</h2>
<p>Export opens your device's share/save interface only when you request it. If you choose a recipient or service, that destination receives the exported file under its own policy. Temporary native export files are cleaned up; the original history take remains until you delete it. Delete individual takes in History. Clear app/site storage to remove local history and progress. Microphone permission can be revoked in device/browser settings.</p>
<h2>Support and educational limits</h2>
<p>If you email support, we receive the message and attachments you choose to send and use them to answer your request. Do not send sensitive recordings unless you intend to share them. The app is an educational practice tool, not speech therapy or a medical/diagnostic assessment. Signal-quality feedback and game stars are not pronunciation grades.</p>
<p>Questions or a request to delete support correspondence: <a href="mailto:support@lazying.art">support@lazying.art</a>. Policy changes will be dated on this page.</p>`);}
export function supportPage(){return page('ClearPair support',`
<p>Practise the sounds or letters that are easy to confuse. All seven apps include Learn, Listen, Practise and local recording History. No account is required.</p>
<h2>No sound?</h2><p>Check device volume, audio output and the installed speech voice for the course language. The interface language does not change the practice language. Cantonese needs an explicit Cantonese voice; a Mandarin-only device intentionally shows an installation message.</p>
<h2>Recording or history help</h2><p>Allow microphone access in device/browser settings. Record a short take, finish it, then use My recording or History to replay it. A waveform shows signal level, not a pronunciation score. Keep a backup through Export; do not clear data or uninstall to troubleshoot before exporting important recordings.</p>
<h2>Contact</h2><p>Email <a href="mailto:support@lazying.art">support@lazying.art</a> with the course, platform, app version and steps that failed. A screenshot is helpful. No password, payment details or personal recording is needed.</p>
<p>Internal beta builds are not public retail availability. <a href="https://github.com/lachlanchen/ClearPair/blob/main/docs/BETA-0.2.0.md">Current beta guide</a>.</p>`);}
