import {readFileSync} from 'node:fs';
export const listings=JSON.parse(readFileSync('store/listings.json','utf8'));
export function betaDescription(app){
 const row=listings[app];if(!row)throw Error('Unknown course');
 return `${row.name}: practise the sounds and letters that are easy to confuse.\n\n${row.focus}\n\nThis is a standalone app with its own course, recordings and progress. Learn the contrast, listen to pairs, play short recall rounds, and record privately with waveform and local History/replay. Eleven interface languages are separate from the course language. Spoken contrasts have automatic experimental on-device practice matching, not calibrated speech accuracy scoring. Game stars and recording signal quality are separate from the match. Device reference voice quality and offline availability vary. No microphone uploads.`;
}
export function betaNotes(app,build=4){
 if(app==='handf'&&build===14)return 'H & F only: iOS rechecks offline speech support each take instead of disabling a language after a transient error. Usable Apple partial words survive request completion, with provisional labels and lower caps. Words are decoded before reference playback. Nearby vowel substitutions retain partial content feedback, never a perfect match. Captured uncertain takes show speech duration and actual recognition in Details. Word match and measured H/F sound remain separate. Offline; no audio uploads. Update without uninstalling and test repeated hat/fat, hit/fit, quiet speech and History replay.';
 if(app==='handf'&&build===13)return betaNotes(app,12)+' Word-only reference ratios never count twice as measured consonant evidence; the word-only cap is enforced.';
 if(app==='handf'&&build===12)return 'H & F only: ambiguous but measured sound now retains a provisional practice score and sound/word/timing analysis instead of a dead-end uncertainty message. Final native fallback words are no longer discarded by the acoustic score threshold. Empty Apple final results use the bundled saved-audio decoder. Word identity never invents a measured sound grade; silence remains unscored. Test repeated hat/fat without restarting, opposite words, quiet speech and History replay. Offline; no audio uploads. Update without uninstalling.';
 if(app==='handf'&&build===11)return 'H & F only: iOS identifies saved English/Mandarin audio with Apple on-device speech and a bundled native offline fallback; no WebView decoder is needed. Word identity and measured consonant detail stay separate. Clear words are not discarded solely by synthetic pitch/boundary failures. Unmeasured sound is labelled; failed-assessment reasons stay with History audio. Android keeps its bundled offline decoder. Final F/V retains acoustic grading. No audio uploads. Try hat/fat, hit/fit, quiet and repeated takes. Update without uninstalling.';
 if(app==='handf'&&build===10)return 'H & F only: offline English/Mandarin word evidence helps uncertain H/F takes on Android and iOS 26.5+. Older iOS keeps acoustic scoring. Quiet words retain weak endings. Word identity and measured sound stay separate; unrelated ASR text alone cannot penalize a take. Final F/V retains acoustic scoring. Experimental practice indices, not calibrated pronunciation accuracy percentages. No audio uploads. Try correct/opposite words, quiet speech, sentences and repeated takes. Update without uninstalling.';
 const row=listings[app];if(!row)throw Error('Unknown course');
 if(build>=9)return `${row.name}\n\n${row.focus}\n\nImproved quiet/short-word scoring. Weak consonant onsets and endings are retained instead of being trimmed away. Record, speak, then pause or tap again to finish.\n\nPair-focused comparison gives the confusing initial, vowel or ending more weight than the shared part of the word. Clear opposite-word matches give low-score feedback, not a missing-recording message. Visible result items show word match, contrast and speech duration; H/F keeps its sound, vowel/word and timing items. The recording controls remain above the result.\n\n${app==='cantonese'?'The B/P example now uses 標 biu1 / 飄 piu1 because the previous 坡 prompt could be read like 波. ':''}This is an experimental local reference comparison, not a calibrated pronunciation accuracy percentage. Tone/mora routes and ungraded explorations retain their separate handling. An offline practice-language voice is required. No microphone uploads. Please try correct/opposite words, quiet short words, immediate speaking, repeated takes and History/replay. Update without uninstalling.`;
 if(build>=8)return `${row.name}\n\n${row.focus}\n\nTap Record once, say the word, then pause. Tap again to stop immediately; no separate Assess step is needed for spoken contrasts. Quiet words spoken immediately now trigger pause detection more reliably.\n\nCompact practice screen: word pair, waveform, Record and score together. The idle countdown and Learn hero are removed. Replay/export and optional score details are below the result. The player bar appears only during playback and cannot cover the recording control.\n\n${app==='handf'?'H/F scoring retains a clear opposite-word comparison when consonant segmentation is uncertain, without awarding a high grade for the shared vowel. Closer to shows acoustic reference similarity, not a transcription. ':''}The native match is an experimental comparison against both offline device voices, not a calibrated pronunciation accuracy percentage. Visual/same-sound exercises remain ungraded. No microphone uploads. Please try selected and opposite words, immediate quiet speech, repeated takes, sentence pauses and History/replay. Update without uninstalling.`;
 if(app==='handf'&&build>=7)return `${row.name}\n\nRecord once, say the word, then pause. Scoring starts automatically after silence or when you tap Stop and score. The Record button stays in place for repeated attempts.\n\nNew consonant-focused on-device scoring compares H/F separately from the vowel and word. English H/F, Mandarin H/F and final F/V have separate acoustic handling. Results show target sound, word match and relative timing, with specific mouth/airflow advice. Sentence mode searches for the displayed word inside the recording. Fourier-derived spectral features and vowel-relative normalization reduce gain and microphone differences.\n\nExperimental reference comparison; human pronunciation accuracy is still being evaluated. No microphone uploads. Keep an offline practice-language voice installed. Please try each word and its opposite, a very short word, an immediate start, a pause inside a sentence, repeated takes and History/replay. Update without uninstalling.`;
 if(build>=7)return `${row.name}\n\n${row.focus}\n\nRecord, speak, then pause: spoken contrast exercises stop after silence and start on-device scoring automatically. Stop and score is also available. The Record button stays in place; repeated takes and their results remain in History. Visual or same-sound script exercises remain explicitly ungraded.\n\nThe experimental 0–100 practice match uses spectral, timing and relative pitch evidence against both displayed reference words. It is reference similarity, not a pronunciation accuracy percentage. An installed offline practice-language voice is required. No microphone uploads. Try the selected word and its opposite, short words, sentences, repeated recording, cancel/retry and History/replay. Update without uninstalling.`;
 if(build>=6)return `${row.name}\n\n${row.focus}\n\nNew experimental on-device practice score: record, finish, then tap Assess my pronunciation. The 0–100 beta match compares your sound with both reference words using spectrum, timing and relative pitch. It is reference similarity, not a pronunciation accuracy percentage or a calibrated grade. No microphone uploads. An installed offline practice-language voice is required.\n\nPlease try a correct word, its opposite, silence, a short word and the sentence option. Repeat several times, cancel an assessment, change cards, and check History/replay. Tell us the selected word, your spoken word and the score. Listening stars stay separate. Update in place; do not uninstall. Internal test only; formal speech accuracy scoring remains under validation.`;
 const changes=build>=5
  ?`Reference playback hardening: correct practice-language voices, no iOS novelty/personal voices, and installed Android voices only.${app==='japanese'?' Isolated kana use explicit Japanese sound readings; displayed kana and contextual furigana stay unchanged.':''}`
  :app==='japanese'
  ?'First standalone Japanese beta: confusing kana, contextual furigana, mora beats and modern stroke replay. Learn cues follow the selected word pair.'
  :'Updated on-device runtime integration, V4 artwork and eleven interface languages, independent of the practice language.';
 return `${row.name}\n\n${row.focus}\n\n${changes}\n\nPlease test repeated pair replay/loop/stop, consecutive microphone takes, waveform, local History/replay and export on iPhone/iPad. On-device scoring remains under validation: game stars and signal quality are not pronunciation grades; speech accuracy scoring is disabled. Device reference voice quality and offline availability vary. No microphone uploads. Internal test build, not a public release. Update in place to preserve earlier recordings; do not uninstall.`;
}
export function fullDescription(app){
 const row=listings[app];if(!row)throw Error('Unknown course');
 return `${row.name}: practise what you mix up. Learn the difference.

${row.focus}

LEARN THE CONTRAST
${app==='japanese'?'Compare easily confused kana, explicit furigana readings and mora beats. Replay modern stroke order from attributed KanjiVG data. Source-backed kana origins are distinct from memory cues; the animation does not reconstruct historical handwriting.':'Explore clear, original schematic pictures and optional learning motion. Use short cues to compare the part that is easy to confuse. Pictures illustrate a principle, not your individual anatomy.'}

LISTEN, REPEAT, REMEMBER
Play both sides back to back. Repeat a pair until you stop, slow the reference, or use a sentence. Short, untimed five-question rounds reward listening or visual recall. Review prioritizes contrasts you have practised.

RECORD AND COMPARE
Tap Record, say the displayed word, then pause. Watch the live waveform; spoken contrast exercises stop after a short silence and start an on-device practice match automatically. Tap again to stop manually. The word pair, Record button and result stay together for repeated attempts. Replay your own take beside the reference, keep a local recording history, and export a backup. The experimental match compares acoustic features with both displayed device-voice references. It is not a pronunciation accuracy percentage or a calibrated assessment. ${app==='handf'?'H/F and final F/V results separately show target-sound evidence, word match and relative timing. ':''}Visual and same-sound script exercises do not receive a spoken distinction score. Recording-signal feedback and listening stars are separate.

YOUR INTERFACE, YOUR PRACTICE LANGUAGE
Choose from eleven interface languages: English, Arabic, Spanish, French, Japanese, Korean, Vietnamese, Simplified Chinese, Traditional Chinese, German or Russian. This does not change the course's practice language. Specialist explanations are English/Chinese; other interfaces label the English fallback.

PRIVATE BY DESIGN
No account, ads or recording uploads. Recordings, review progress and stars stay on your device. Device speech providers may use a network voice; voice availability, quality and offline support vary. Install the practice-language voice when needed. ${app==='cantonese'?'Cantonese needs a Cantonese voice; Mandarin is not substituted. ':''}Clearing app or website data can remove recordings, so export anything you want to keep.

An educational practice tool, not speech therapy or a validated diagnostic assessment.
Support: support@lazying.art
Privacy: https://language-agent.lazying.art/privacy.html`;
}
