// Same nine columns as ui-catalog. Content notes retain their visible source
// language where a specialist translation has not been reviewed.
export const mapCatalog = {
 'Letter name':['اسم الحرف','Nombre de la letra','Nom de la lettre','文字の名前','글자 이름','Tên chữ','字母名稱','Buchstabenname','Название буквы'],
 'Tones':['النغمات','Tonos','Tons','声調','성조','Thanh điệu','聲調','Töne','Тоны'],
 'Initials':['الأصوات الأولية','Iniciales','Initiales','声母','성모','Âm đầu','聲母','Anlaute','Начальные согласные'],
 'Finals':['نهايات المقاطع','Finales','Finales','韻母','운모','Vần','韻母','Silbenauslaute','Финали'],
 'Spelling and context':['الكتابة والسياق','Ortografía y contexto','Orthographe et contexte','綴りと文脈','표기와 문맥','Chính tả và ngữ cảnh','拼寫與語境','Schreibung und Kontext','Написание и контекст'],
 'Rhymes':['قوافي المقاطع','Rimas silábicas','Rimes syllabiques','韻母','운모','Vần','韻母','Silbenreime','Рифмы слогов'],
 'Rare rhymes':['قوافي نادرة','Rimas poco frecuentes','Rimes rares','まれな韻母','드문 운모','Vần hiếm','罕見韻母','Seltene Silbenreime','Редкие рифмы'],
 'Codas and syllabic nasals':['نهايات المقاطع والأنفيات المقطعية','Finales y nasales silábicas','Codas et nasales syllabiques','韻尾と音節主音の鼻音','종성과 성절 비음','Âm cuối và âm mũi tạo âm tiết','韻尾與成音節鼻音','Auslaute und silbische Nasale','Конечные звуки и слоговые носовые'],
 'Alphabet names':['أسماء الحروف','Nombres de las letras','Noms des lettres','アルファベットの名前','알파벳 이름','Tên chữ cái','字母名稱','Buchstabennamen','Названия букв'],
 'Consonants':['الصوامت','Consonantes','Consonnes','子音','자음','Phụ âm','輔音','Konsonanten','Согласные'],
 'Vowels and glides':['الحركات والانزلاقات الصوتية','Vocales y deslizamientos','Voyelles et glissements','母音と音の移動','모음과 활음','Nguyên âm và âm lướt','元音與滑動','Vokale und Gleitbewegungen','Гласные и скольжения'],
 'Initial letters':['حروف بداية المقطع','Letras iniciales','Lettres initiales','初声の文字','초성 글자','Chữ âm đầu','聲母字母','Anlautbuchstaben','Буквы начала слога'],
 'Vowel letters':['حروف الحركات','Letras vocálicas','Lettres voyelles','母音字母','모음 글자','Chữ nguyên âm','元音字母','Vokalbuchstaben','Гласные буквы'],
 'Final sound categories':['فئات أصوات نهاية المقطع','Categorías de sonidos finales','Catégories de sons finaux','終声の音の分類','종성 소리 범주','Nhóm âm cuối','韻尾音類','Auslautkategorien','Категории конечных звуков'],
 'Final spellings':['كتابة نهايات المقاطع','Grafías finales','Graphies finales','終声の表記','종성 표기','Cách viết âm cuối','韻尾寫法','Auslautschreibungen','Написание конечных согласных'],
 'Letter names and sound examples':['أسماء الحروف وأمثلة الأصوات','Nombres de letras y ejemplos de sonidos','Noms des lettres et exemples sonores','文字名と音の例','글자 이름과 발음 예시','Tên chữ và ví dụ âm','字母名稱與例音','Buchstabennamen und Lautbeispiele','Названия букв и примеры звуков'],
 'Hamza':['الهمزة','Hamza','Hamza','ハムザ','함자','Hamza','Hamza','Hamza','Хамза'],
 'Short and long vowels':['الحركات القصيرة والطويلة','Vocales cortas y largas','Voyelles brèves et longues','短母音と長母音','단모음과 장모음','Nguyên âm ngắn và dài','短元音與長元音','Kurze und lange Vokale','Краткие и долгие гласные'],
 'Marks and context':['العلامات والسياق','Signos y contexto','Signes et contexte','記号と文脈','기호와 문맥','Dấu và ngữ cảnh','符號與語境','Zeichen und Kontext','Знаки и контекст'],
 'Voiced and semi-voiced hiragana':['هيراغانا المجهورة وشبه المجهورة','Hiragana sonoro y semisonoro','Hiragana sonore et semi-sonore','ひらがなの濁音・半濁音','히라가나 탁음과 반탁음','Hiragana hữu thanh và bán hữu thanh','濁音與半濁音平假名','Stimmhafte und halbstimmhafte Hiragana','Звонкая и полузвонкая хирагана'],
 'Voiced and semi-voiced katakana':['كاتاكانا المجهورة وشبه المجهورة','Katakana sonoro y semisonoro','Katakana sonore et semi-sonore','カタカナの濁音・半濁音','가타카나 탁음과 반탁음','Katakana hữu thanh và bán hữu thanh','濁音與半濁音片假名','Stimmhafte und halbstimmhafte Katakana','Звонкая и полузвонкая катакана'],
 'Contracted hiragana':['هيراغانا المركبة','Hiragana combinado','Hiragana combiné','ひらがなの拗音','히라가나 요음','Hiragana ghép','平假名拗音','Kombinierte Hiragana','Сочетания хираганы'],
 'Contracted katakana':['كاتاكانا المركبة','Katakana combinado','Katakana combiné','カタカナの拗音','가타카나 요음','Katakana ghép','片假名拗音','Kombinierte Katakana','Сочетания катаканы'],
 'Common loanword combinations':['تركيبات الكلمات الدخيلة الشائعة','Combinaciones de préstamos frecuentes','Combinaisons courantes d’emprunts','よく使う外来音の組み合わせ','자주 쓰는 외래어 조합','Tổ hợp từ mượn thường gặp','常用外來音組合','Häufige Fremdwortkombinationen','Частые сочетания в заимствованиях'],
 'Sound and letter map':['خريطة الأصوات والحروف','Mapa de sonidos y letras','Carte des sons et des lettres','音と文字の一覧','소리와 글자 지도','Bảng âm và chữ','聲音與字母表','Laut- und Buchstabenübersicht','Карта звуков и букв'],
 'Sound groups':['مجموعات الأصوات','Grupos de sonidos','Groupes de sons','音のグループ','소리 그룹','Nhóm âm','聲音分組','Lautgruppen','Группы звуков'],
 'Playback type':['نوع التشغيل','Tipo de reproducción','Type de lecture','再生する内容','재생 유형','Loại phát âm','播放類型','Wiedergabetyp','Тип воспроизведения'],
 'Sound example':['مثال صوتي','Ejemplo de sonido','Exemple sonore','音の例','발음 예시','Ví dụ âm','例音','Lautbeispiel','Пример звука'],
 'No verified audio example':['لا يوجد مثال صوتي متحقق منه','Sin ejemplo de audio verificado','Aucun exemple audio vérifié','確認済みの音声例はありません','검증된 음성 예시 없음','Chưa có ví dụ âm đã xác minh','暫無核實例音','Kein geprüftes Audiobeispiel','Нет проверенного аудиопримера'],
 'Back-to-back tone grid':['جدول النغمات المتتابعة','Tabla de tonos consecutivos','Grille des tons successifs','声調の連続練習表','연속 성조 표','Bảng thanh điệu nối tiếp','連續聲調表','Tabelle aufeinanderfolgender Töne','Таблица последовательностей тонов'],
 'Reference map: listening and recall, not a pronunciation grade.':['خريطة مرجعية للاستماع والتذكر، وليست تقييماً للنطق.','Mapa de referencia para escuchar y recordar, no una nota de pronunciación.','Carte de référence pour écouter et mémoriser, pas une note de prononciation.','聴く・思い出すための参考表です。発音の採点ではありません。','듣기와 기억을 위한 참고표이며 발음 점수가 아니에요.','Bảng tham khảo để nghe và nhớ, không phải điểm phát âm.','參考表：用於聆聽與回憶，不是發音評分。','Referenz zum Hören und Erinnern, keine Aussprachebewertung.','Справочник для прослушивания и запоминания, не оценка произношения.'],
 'Separate syllables with a pause. This listening drill is not connected-speech scoring; Mandarin 3 + 3 changes in a phrase.':['مقاطع منفصلة مع وقفة. هذا تدريب استماع وليس تقييماً للكلام المتصل؛ تتغير النغمة 3 + 3 في عبارات الماندرين.','Sílabas separadas por una pausa. Es escucha, no evaluación del habla continua; 3 + 3 cambia en una frase en mandarín.','Syllabes séparées par une pause. Exercice d’écoute, pas évaluation de la parole liée ; 3 + 3 change en contexte en mandarin.','音節の間に間を置きます。連続発話の採点ではなく聴き分け練習です。普通話の3声＋3声は文中で変調します。','음절 사이에 쉼이 있어요. 연속 발화 채점이 아닌 듣기 연습이며 중국어 3성 + 3성은 구에서 변해요.','Các âm tiết có khoảng dừng. Đây là luyện nghe, không chấm lời nói liền mạch; thanh 3 + 3 đổi trong cụm tiếng Quan thoại.','音節之間有停頓。這是聽辨練習，不是連續語流評分；普通話短語中的三聲加三聲會變調。','Getrennte Silben mit Pause. Hörübung, keine Bewertung verbundener Sprache; Mandarin 3 + 3 verändert sich im Ausdruck.','Между слогами пауза. Это слуховая тренировка, не оценка связной речи; сочетание 3 + 3 в китайской фразе меняется.'],
} as const;

// Explicit script variants for the authored specialist notes. Keep these out
// of automatic character-by-character conversion (e.g. 發/髮 and 后/後).
export const mapTraditionalNotes:Record<string,string> = {
 'Standard Mandarin: Pinyin initials, common finals, four tones and spelling conventions. Not a list of every Han character.':'普通話：拼音聲母、常用韻母、四聲與拼寫規則；不是所有漢字的列表。',
 'Hear the initial inside a real syllable. Pinyin b/d/g contrast with p/t/k mainly through aspiration, not English-style voicing.':'在真實音節內聽聲母。b/d/g 與 p/t/k 主要區別在送氣，不是英語式清濁。',
 'The label is Pinyin, not IPA. iu/ui/un abbreviate iou/uei/uen; j/q/x + u represents ü. Final i differs in zi, zhi and ji.':'標籤是拼音，不是國際音標。iu/ui/un 分別縮寫 iou/uei/uen；j/q/x 後的 u 表示 ü。zi、zhi、ji 的 i 音質不同。',
 'y/w are Pinyin spelling conventions. Neutral tone is light and context-dependent; it is not another fixed isolated contour.':'y/w 是拼音拼寫規則。輕聲較輕，隨語境變化，不是另一個固定孤立調型。',
 'Teaching contours use relative pitch, not a fixed Hz target. Word recognition is not tone measurement.':'聲調示意使用相對音高，不是固定赫茲目標；識別詞語不等於測量聲調。',
 'Hong Kong Cantonese: Jyutping initials, common rhymes, codas, syllabic nasals and six tone categories. Rare rhymes without a verified spoken example stay silent.':'香港粵語：粵拼聲母、常用韻母、韻尾、成音節鼻音與六個聲調。沒有核實例音的罕見韻母不播放。',
 'Jyutping j is a y-like glide. n/l and initial ng vary between speakers; variation is not automatically an error.':'粵拼 j 是類似英語 y 的滑音。n/l 與聲母 ng 因說話者而異，不自動判作錯誤。',
 'The label is Jyutping. Vowel quality can change before a coda: sin/sing are not only n/ng. Stop codas are usually unreleased.':'標籤是粵拼。元音在韻尾前可能改變：sin/sing 不只是 n/ng。塞音韻尾通常不釋放。',
 'Listed in the Jyutping scheme; no unverified device pronunciation is played here.':'粵拼方案所列韻母；這裡不播放未經核實的裝置讀音。',
 'p/t/k stop the syllable without an extra vowel. Checked tones use 1/3/6, not three additional pitch categories.':'p/t/k 收住音節，不添加元音。入聲用 1/3/6，不是額外三個音高類別。',
 'General American reference: 26 letter names, consonants and vowel examples. Letter names are not the sounds of every word. Regional vowel mergers are accepted variation.':'通用美式參考：26 個字母名稱、輔音和元音例詞。字母名稱不等於每個詞裡的讀音；地域元音合流是允許變體。',
 'Hear the complete letter name, not a phoneme accuracy test.':'聽完整字母名稱，不作為音位準確度測驗。',
 'Compare place, airflow, voicing and position. A word example keeps a short sound audible; it is not an isolated-letter recording.':'比較部位、氣流、清濁與位置。短音放在例詞中更易聽，不是孤立字母錄音。',
 'Quality, lip shape and movement matter as well as duration. ɔ/ɑ can merge. ə and ɚ normally occur unstressed.':'音質、唇形和滑動與時長同樣重要。ɔ/ɑ 可合流；ə 與 ɚ 通常不重讀。',
 'Modern Hangul: 19 initial letters, 21 vowel letters, 27 final spellings and seven final sound categories. Spelling does not uniquely determine connected-speech pronunciation.':'現代韓文：19 個聲母字母、21 個元音字母、27 個韻尾寫法與七類收尾聲音。拼寫不唯一決定連續語流發音。',
 'Choose a letter name or a syllable example. Initial ㅇ is silent; ㄹ changes with position. Plain, aspirated and tense are three categories.':'可聽字母名稱或音節例子。聲母 ㅇ 不發音；ㄹ 隨位置變化。鬆音、送氣音、緊音是三類。',
 'Romanization is a reading aid, not English pronunciation. ㅐ/ㅔ often merge; ㅚ/ㅟ and ㅢ have accepted contextual variants.':'羅馬字是讀音輔助，不按英語讀。ㅐ/ㅔ 常合流；ㅚ/ㅟ 與 ㅢ 有允許的語境變體。',
 'Before a pause there are seven consonant endings. A following vowel or consonant can change their realization.':'停頓前有七類輔音收尾；後接元音或輔音會改變實際讀音。',
 'Examples are read as whole words. Complex finals need context; do not pronounce both written consonants as separate syllables.':'例子按整詞讀。複合韻尾需要語境，不把兩個輔音讀成額外音節。',
 'Modern Standard Arabic: 28 base letters, hamza, vowel length and marks. Dialect realizations may differ; letter names and syllables are separate tasks.':'現代標準阿拉伯語：28 個基礎字母、hamza、元音長短與符號。方言音值可能不同；字母名稱與音節是不同任務。',
 'Short a syllables make the consonant audible. Alif is not simply another consonant; hamza represents a glottal stop. Do not strain your throat.':'短 a 音節讓輔音更易聽。alif 不是簡單的另一個輔音；hamza 表示聲門塞音。不要用力擠喉。',
 'The written seat and the sound are different layers. This example is a sound, not the name of the seat letter.':'字形承載位置與聲音是兩層內容。這裡的例子是讀音，不是承載字母名稱。',
 'Keep quality similar and compare timing within a syllable, rather than using one fixed duration for every speaker.':'保持相近音質，在音節內比較時長，不給所有說話者設同一時長。',
 'Sukun means no vowel, not silence for the whole letter. Shadda holds a consonant. Tanwin and endings change at a pause.':'sukun 表示沒有元音，不是整個字母不發音。shadda 讓輔音停留；tanwin 與詞尾在停頓時會變化。',
 'Modern kana: 46 basic forms per script, voiced/semi-voiced kana and standard contracted sounds. Common loanword combinations and mora timing are separate; this is not all kanji.':'現代假名：每套 46 個基本字形、濁音/半濁音與標準拗音。常用外來音組合和拍子另列；不包含所有漢字。',
 'Kana examples use explicitly authored Japanese readings. Some spellings share a sound; the map is not a scored discrimination quiz.':'假名使用明確編寫的日語讀音。部分寫法讀音相同；本表不是評分辨音測驗。',
 'Pronunciations vary with the word and speaker. ヴ may be realized like b; do not diagnose that variation as an error.':'讀音隨詞語和說話者變化。ヴ 可讀得接近 b，不將這種變體診斷為錯誤。',
 '1: keep a high, steady pitch within your own comfortable range.':'一聲：在自己舒適的音域內保持高平。',
 '2: rise from the middle toward the higher part of your range.':'二聲：從中音向較高處上升。',
 '3: reach the low part of your range. A full rise is not required in every context.':'三聲：到達音域低處。並非所有語境都要完整回升。',
 '4: start higher and fall. Do not squeeze your throat.':'四聲：從較高處下降，不要擠喉。',
 'Keep the syllable the same; compare the pitch movement and register.':'保持音節相同，比較音高走向和音區。',
 'Use your own pitch range. Try a carrier sentence when level tones are hard to compare.':'使用自己的音域。平調不易比較時，可試短句模式。',
 'Some speakers merge tone contrasts. These are reference patterns, not an accent diagnosis. A word match alone cannot measure tone.':'部分說話者會合併聲調。這些是參考模式，不是口音診斷；識別詞語本身不能測量聲調。',
 'Third tone changes in connected speech. These single-syllable sketches are not fixed pitch requirements for every sentence. Word recognition cannot measure tone.':'三聲會隨連續語流變化。單音節示意不是每個句子的固定音高要求；識別詞語不能測量聲調。',
};
