// Same nine translated columns as ui-catalog; English/Simplified Chinese live
// beside the UI. These messages never promise a model that is not packaged.
export const scoreCatalog = {
 'Recorded word':['الكلمة المسجلة','Palabra grabada','Mot enregistré','録音した単語','녹음한 단어','Từ đã ghi âm','錄製的詞','Aufgenommenes Wort','Записанное слово'],
 'Pronunciation assessment':['تقييم النطق','Evaluación de pronunciación','Évaluation de prononciation','発音評価','발음 평가','Đánh giá phát âm','發音評分','Aussprachebewertung','Оценка произношения'],
 'Assess my pronunciation':['قيّم نطقي','Evaluar mi pronunciación','Évaluer ma prononciation','発音を評価','내 발음 평가','Đánh giá phát âm của tôi','評估我的發音','Meine Aussprache bewerten','Оценить моё произношение'],
 'On this device. No audio uploads.':['على هذا الجهاز. دون رفع الصوت.','En este dispositivo. Sin subir audio.','Sur cet appareil. Aucun envoi audio.','端末内で処理。音声は送信しません。','이 기기에서 처리하며 음성을 업로드하지 않아요.','Trên thiết bị này. Không tải âm thanh lên.','在此裝置執行，不上傳錄音。','Auf diesem Gerät. Keine Audio-Uploads.','На этом устройстве. Без загрузки аудио.'],
 'Analysing the target sound…':['جارٍ تحليل الصوت المستهدف…','Analizando el sonido objetivo…','Analyse du son ciblé…','練習する音を分析中…','목표 소리 분석 중…','Đang phân tích âm cần luyện…','正在分析目標音…','Zielklang wird analysiert…','Анализируем нужный звук…'],
 'Record first, then assess the confusing sound.':['سجّل أولاً، ثم قيّم الصوت الملتبس.','Graba primero y evalúa el sonido que confundes.','Enregistrez, puis évaluez le son difficile à distinguer.','まず録音してから、混同しやすい音を評価します。','먼저 녹음하고 헷갈리는 소리를 평가해요.','Ghi âm trước, rồi đánh giá âm dễ nhầm.','先錄音，再評估容易混淆的音。','Nimm zuerst auf und bewerte dann den verwechselten Laut.','Сначала запишите, затем оцените трудный для различения звук.'],
 'Estimated target-contrast score, not a diagnosis.':['تقدير للتمييز الصوتي المستهدف، وليس تشخيصاً.','Puntuación estimada del contraste objetivo, no un diagnóstico.','Estimation du contraste ciblé, pas un diagnostic.','対象音の対比に対する推定スコアであり、診断ではありません。','목표 소리 대비의 추정 점수이며 진단이 아니에요.','Điểm ước lượng cho đối lập âm, không phải chẩn đoán.','目標音對比的估計分數，不是診斷。','Geschätzter Zielkontrast-Wert, keine Diagnose.','Оценка целевого звукового различия, не диагноз.'],
 'This is an ungraded exploration, not a spoken contrast test.':['هذا استكشاف بلا درجات، لا اختبار تمييز نطق.','Esta exploración no se puntúa; no es una prueba de contraste hablado.','Exploration sans note, pas un test de contraste oral.','これは採点しない比較練習で、発音対比のテストではありません。','채점하지 않는 탐색이며 발음 대비 시험이 아니에요.','Đây là khám phá không chấm điểm, không phải kiểm tra đối lập phát âm.','這是不計分的探索，不是發音對比測試。','Eine unbewertete Erkundung, kein gesprochener Kontrasttest.','Это исследование без оценки, не тест звукового различия.'],
 'No reliable speech signal. Check the microphone and try again.':['لا توجد إشارة كلام موثوقة. افحص الميكروفون وحاول مجدداً.','No hay señal de voz fiable. Comprueba el micrófono y vuelve a probar.','Pas de signal vocal fiable. Vérifiez le micro et réessayez.','信頼できる音声信号がありません。マイクを確認して再試行してください。','신뢰할 수 있는 음성 신호가 없어요. 마이크를 확인하고 다시 시도하세요.','Không có tín hiệu giọng nói đáng tin cậy. Kiểm tra micrô rồi thử lại.','沒有可靠語音訊號，請檢查麥克風後重試。','Kein zuverlässiges Sprachsignal. Prüfe das Mikrofon und versuche es erneut.','Нет надёжного речевого сигнала. Проверьте микрофон и повторите.'],
 'The on-device pronunciation models are still being validated. No grade is invented.':['نماذج النطق المحلية ما زالت قيد التحقق. لا نختلق درجات.','Los modelos locales de pronunciación siguen en validación. No se inventan puntuaciones.','Les modèles de prononciation sur appareil sont encore en validation. Aucune note n’est inventée.','端末内の発音モデルは検証中です。スコアを作り上げることはありません。','기기 내 발음 모델은 아직 검증 중이며 점수를 만들어 내지 않아요.','Mô hình phát âm trên thiết bị vẫn đang được kiểm định. Không tạo điểm giả.','裝置端發音模型仍在驗證中，不會編造分數。','Die lokalen Aussprachemodelle werden noch geprüft. Es werden keine Werte erfunden.','Модели произношения на устройстве ещё проверяются. Оценки не выдумываются.'],
 'Assessment stopped. Your recording is safe.':['توقف التقييم. تسجيلك محفوظ.','Evaluación detenida. Tu grabación se conserva.','Évaluation arrêtée. Votre enregistrement est conservé.','評価を停止しました。録音は保持されています。','평가를 중지했어요. 녹음은 유지돼요.','Đã dừng đánh giá. Bản ghi vẫn được giữ.','評分已停止，錄音仍保留。','Bewertung gestoppt. Deine Aufnahme bleibt erhalten.','Оценка остановлена. Запись сохранена.'],
 'The target could not be located reliably. Try the sentence option.':['تعذّر تحديد الصوت المستهدف بثقة. جرّب خيار الجملة.','No se pudo localizar el sonido objetivo con fiabilidad. Prueba la opción de frase.','Le son ciblé n’a pas pu être localisé avec fiabilité. Essayez une phrase.','対象の音を確実に特定できません。短い文で練習してみてください。','목표 소리를 신뢰할 수 있게 찾지 못했어요. 문장 옵션을 사용해 보세요.','Không xác định chắc chắn được âm mục tiêu. Hãy thử tùy chọn câu.','無法可靠定位目標音，請嘗試短句模式。','Der Ziellaut konnte nicht zuverlässig gefunden werden. Versuche die Satzoption.','Не удалось надёжно найти нужный звук. Попробуйте вариант с предложением.'],
 'The sound is uncertain. Compare the pair and record again.':['الصوت غير مؤكد. قارن الزوج ثم سجّل مجدداً.','El sonido no es claro. Compara el par y vuelve a grabar.','Le son est incertain. Comparez la paire et réenregistrez.','音の区別が不確かです。ペアを比べて録音し直してください。','소리 구분이 불확실해요. 쌍을 비교하고 다시 녹음하세요.','Âm chưa rõ ràng. So sánh cặp rồi ghi âm lại.','音的區別不夠確定，請比較詞對後重錄。','Der Laut ist unsicher. Vergleiche das Paar und nimm erneut auf.','Звук определён неуверенно. Сравните пару и запишите снова.'],
 'Local assessment is unavailable for this take. You can still replay it.':['التقييم المحلي غير متاح لهذا التسجيل. يمكنك إعادة تشغيله.','La evaluación local no está disponible para esta grabación. Puedes reproducirla.','L’évaluation locale est indisponible pour cet essai. Vous pouvez le réécouter.','この録音は端末内で評価できません。再生は可能です。','이 녹음의 기기 내 평가는 사용할 수 없지만 재생은 가능해요.','Chưa thể đánh giá cục bộ bản ghi này. Bạn vẫn có thể nghe lại.','這段錄音暫時無法在裝置端評分，仍可回放。','Diese Aufnahme kann lokal nicht bewertet werden. Du kannst sie weiterhin abspielen.','Локальная оценка этой записи недоступна. Её можно прослушать.'],
} satisfies Record<string,readonly [string,string,string,string,string,string,string,string,string]>;
